### ISSUE TITLE
make progress bar in video context one track

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-client#38]
**Describe the bug**
when previewing a clip the progress bar as multiple tracks

**To Reproduce**
- start client and server
- go to programme script in client (eg [/projects/`:id`/paperedits/`:id`](http://localhost:3000/#/projects/1cjw29xii80000ird74yb19swa/paperedits/1112cjw29xii80000ird74yb19swa) )
- see video context preview

**Expected behavior**
to see one track in progress bar instead of severals

**Screenshots**

<img width="437" alt="Screen Shot 2019-07-04 at 16 37 20" src="https://user-images.githubusercontent.com/4661975/60674297-1b232e80-9e7a-11e9-9f90-365af038a9cb.png">

**Additional context**
at the moment working of this branch [`bbc/digital-paper-edit-client/ui-tweaks`](https://github.com/bbc/digital-paper-edit-client/tree/ui-tweaks)

**Comment by pietrop** [comment]
I can see the height here in `.../PreviewCanvas/VideoContextProgressBar.module.css` is what puts all the tracks all on different rows

```css
.papercutsPlayerProgressTrack{
  height: 8px;
  opacity: 0.2;
  background: black;
}
```

But if we collapse them to one line we need to add a border of a different colour to mark them as distinct clips, but didn't have much luck in adding a border colour.

**Comment by emettely** [comment]
Done as part of #41 and #47
