### ISSUE TITLE
Clicking on progress bar in programmes script video preview  crashes the app

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-client#39]
**Describe the bug**
clicking progress bar of Video preview (video context) component in programme script crashes the app. 

**To Reproduce**
1. Go to programme script in client [http://localhost:3000/#/projects/1cjw29xii80000ird74yb19swa/paperedits/1112cjw29xii80000ird74yb19swa](http://localhost:3000/#/projects/1cjw29xii80000ird74yb19swa/paperedits/1112cjw29xii80000ird74yb19swa)
2. Select some text from transcript
3. Click on 'Add Selection' (in the programme script)
4. click 'Refresh Preview' (in the programme script)
5. Click anywhere in the progress bar for video context

```
TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite
```

**Expected behavior**
Expect to be able to click around the progress bar without crashing the app

**Screenshots**
![Screen Shot 2019-07-11 at 15 54 06](https://user-images.githubusercontent.com/4661975/61061445-30590980-a3f4-11e9-9882-1f8fcfc46b12.png)

**Desktop (please complete the following information):**
 - OS:  OS X - 10.13.6
 - Browser Chrome - Version 75.0.3770.100 (Official Build) (64-bit)
 - Version `1.0.2`

**Additional context**
_NA_

**Comment by emettely** [comment]
Resolved as part of https://github.com/bbc/digital-paper-edit-client/pull/47
