### ISSUE TITLE
BBC Video Context - How Tos

### ISSUE THREAD

**Issue by pietrop** [bbc/digital-paper-edit-client#45]
Some things to figure out about how [BBC Video Context React wrapper](https://github.com/bbc/digital-paper-edit-client/tree/master/src/Components/PaperEdits/PaperEdit/ProgramScript/PreviewCanvas) could work to integrate with DPE functionalities 

- [x] 1. How to show **total duration** of media for a playlist input
- [x] 2. How to show showing **current time** while playing
- [x] 3. How to **flatten the progress bar** (see  @melnyczuk 's PR https://github.com/bbc/digital-paper-edit-client/pull/41 & https://github.com/bbc/digital-paper-edit-client/pull/41#issuecomment-514225148)
- [x] 4. How to make the BBC Video context jump to a specific point, eg equivalent of **`.currentTime = `**  for HTML5 video/audio element. (eg to enable functionalities such as click on a word in programme script, after calculating offset etc..)
- [x] 5. how to **update a playlist** in video context

cc @PTaylour @melnyczuk

**Comment by emettely** [comment]
Are there any known issues around laggy playback? We will need to look at this in more detail, but noticed it when trying out an electron app version of Digital Paper Edit.

**Comment by pietrop** [comment]
## 1. total duration
From the docs [`.duration`](https://bbc.github.io/VideoContext/api/module-VideoContext.html#duration)

>Get the time at which the last node in the current internal timeline finishes playing.

```js
var canvasElement = document.getElementById("canvas");
var ctx = new VideoContext(canvasElement);
console.log(ctx.duration); //prints 0

var videoNode = ctx.video("video.mp4");
videoNode.connect(ctx.destination);
videoNode.start(0);
videoNode.stop(10);

console.log(ctx.duration); //prints 10

ctx.play();
```

## 2.  current time
[`.currentTime`](https://bbc.github.io/VideoContext/api/module-VideoContext.html#currentTime)

>Get how far through the internal timeline has been played.
>Getting this value will give the current playhead position. Can be used for updating timelines.

```js
var canvasElement = document.getElementById("canvas");
var ctx = new VideoContext(canvasElement);
var videoNode = ctx.video("video.mp4");
videoNode.connect(ctx.destination);
videoNode.start(0);
videoNode.stop(10);
ctx.play();
setTimeout(() => console.log(ctx.currentTime),1000); //should print roughly 1.0
````

## 3 flatten the progress bar
🤷‍♂  (see Howard’s PR https://github.com/bbc/digital-paper-edit-client/pull/41 & https://github.com/bbc/digital-paper-edit-client/pull/41#issuecomment-514225148)

##  4 . How to make the BBC Video context jump to a specific point, eg equivalent of `.currentTime =`
Similarly to `.currentTime` in HTML5 media, it can be used both as a get and as a set, from BBC Video Context [`.currentTime`](https://bbc.github.io/VideoContext/api/module-VideoContext.html#currentTime) docs.

as a set

```js
var canvasElement = document.getElementById("canvas");
var ctx = new VideoContext(canvasElement);
var videoNode = ctx.video("video.mp4");
videoNode.connect(ctx.destination);
videoNode.start(0);
videoNode.stop(20);
ctx.currentTime = 10; // seek 10 seconds in
ctx.play();https://github.com/bbc/digital-paper-edit-client/issues/45#
```
## 5. **update playlist**

Maybe is a matter of exposing `loadPlaylist` [`/bbc/digital-paper-edit-client/src/Components/PaperEdits/PaperEdit/ProgramScript/PreviewCanvas/VideoContextViewer.js#L35`](https://github.com/bbc/digital-paper-edit-client/blob/master/src/Components/PaperEdits/PaperEdit/ProgramScript/PreviewCanvas/VideoContextViewer.js#L35)

However it might be necessary to clear the nodes in the timeline first. 

>The VideoContext now also has a `reset()` method, which as well as automatically calling destroy on all nodes will also remove all callbacks registered to the VideoContext.

from https://github.com/bbc/VideoContext/issues/37#issuecomment-291462470

>Destroy all nodes in the graph and reset the timeline. After calling this any created nodes will be unusable.
from docs [`reset()`](https://bbc.github.io/VideoContext/api/module-VideoContext.html#reset)


## Other
Other interesting once found in the docs, that can be useful to improve the preview player functionalities 

- [`playbackRate`](https://bbc.github.io/VideoContext/api/module-VideoContext.html#playbackRate)
