### ISSUE TITLE
On save, transcript's detail disappears and becomes undefined in programme script

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-client#49]
**Describe the bug**
This is a bug in the `ui-tweaks` branch in changes between #40 (including) to the most recent changes and needs to be resolved before ui-tweaks can be merged in into master.
Transcript, on update loses details in the cards and in the Programme Script UI becomes undefined.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click a transcript
2. In transcript editing UI click "save"
3. Go back to project page
4. *See missing details (icon + description)*
5. Go to programmme script tab
6. *See transcript show on the left hand side as "undefined"*

**Expected behavior**
No missing details after save or undefined state of transcript.

**Screenshots**

Seen:
<img width="1375" alt="Screen Shot 2019-08-30 at 13 48 12" src="https://user-images.githubusercontent.com/8188418/64022181-8f521980-cb2d-11e9-80f1-4013cdeda5e4.png">
<img width="576" alt="Screen Shot 2019-08-30 at 13 46 37" src="https://user-images.githubusercontent.com/8188418/64022184-90834680-cb2d-11e9-8049-27d8eb227e66.png">

Expected:
<img width="1138" alt="Screen Shot 2019-08-30 at 13 53 56" src="https://user-images.githubusercontent.com/8188418/64022240-a7c23400-cb2d-11e9-8658-89ccd5c9ca9d.png">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser firefox

**Comment by pietrop** [comment]
👋 Something that might help with the troubleshooting, is to know if this is when the app is used with electron or the server backend?

**Comment by emettely** [comment]
> 👋 Something that might help with the troubleshooting, is to know if this is when the app is used with electron or the server backend?

This is running a local dev version of API (master) and ui-tweaks.

**Comment by pietrop** [comment]
It might be to do with this https://github.com/bbc/digital-paper-edit-client/pull/48#issuecomment-526609727 - master was up to date with integration with both backends. You might want to re test after you recent merge. and see if the error persist. 🤞 is gone.
