### ISSUE TITLE
Rapid User Testing with shortlisted UX features (Re-order and Transfer)

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-client#55]
**Is your feature request related to a problem? Please describe.**
We would like to make informed decisions when developing an idea further and taking it to development. Therefor we are conducting the rapid testing sessions with actual users to gather their feedback and opinion on our shortlisted ideas. 

**Methodology**
Finding, 30 mins testing with paper, evaluation and analysis.
The number o participants will depend on whether some of the people who approached us are willing to give feedback again.

We are separating testing sessions for 'Reordering' and 'Transfer' to keep the sessions short.

**Schedule for testing**
https://paper.dropbox.com/doc/Research-II-schedule-and-content--Ak4iKgyNmi200lb4giW81FGeAQ-ElAKmqWz4hAxhMB6yq8Z4

**Discussion guide** 
https://paper.dropbox.com/doc/DPE-Rapid-in-house-testing--Ak4KpHaXZmOpPRV0H9VF8040AQ-c2OJVZMlfdPEWT4kcQJIy

**Comment by nganthi** [comment]
**Preparation for Rapid testing**
- Correspondence with volunteers
- Project overview email
- Revising discussion guide
- Update Confluence documentation
- Preparing workshop to shortlist reordering

**Comment by nganthi** [comment]
### Deliverables

Wireframes for testing
[Reorder ](https://app.zeplin.io/project/5ce554083480691e05af2f74/dashboard?seid=5d80e463bbf60588af468642)
[Transfer ](https://app.zeplin.io/project/5ce554083480691e05af2f74/dashboard?seid=5d80e332ac05be7898f13e67)
[Discussion guide](https://paper.dropbox.com/doc/DPE-Rapid-in-house-testing--Ak4KpHaXZmOpPRV0H9VF8040AQ-c2OJVZMlfdPEWT4kcQJIy)
Rating form 
[Notetaking ](https://docs.google.com/spreadsheets/d/1sHxVes851-7W72mrkhG_t7JuYdEkPZoU8aW-gDF3-WU/edit?usp=sharing)
