### ISSUE TITLE
UX investigation: Duplicate for versioning - Programme Script only

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-client#75]
users should be able to duplicate content in order to version: e.g. when re-versioning long format content to shorter format and multiple programmes.

**Comment by nganthi** [comment]
Wireframes on Zeplin: https://app.zeplin.io/project/5ce554083480691e05af2f74/dashboard?seid=5dad79893b7725126d07cddc

**Comment by emettely** [comment]
Feature has been implemented as part of workspace-v2  https://github.com/bbc/digital-paper-edit-firebase/compare/workspace-v2?expand=1
