### ISSUE TITLE
Implement playback on double-click on text for Programme Script (symmetric to Transcript)

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-client#85]
PR LINK: https://github.com/bbc/digital-paper-edit-firebase/pull/67
## Is your feature request related to a problem? Please describe.

Users expect to be able to playback when double-clicking text in the programme script.
This is also expected because the same interaction is available for the Transcript.

The interaction is as follows:
1. user double clicks a word
2. the video starts playing back at the starting point of a word
3. the words in the transcription highlights in time with the video

## Describe the solution you'd like
Design and implement the interaction described above in the Programme Script.

**Comment by allishultes** [comment]
PaperEdit: 
```
{
  start: // used for VC
  end: 
  words: [
    start: // need to be made relative to VC 
    end: 
  ],
  vcStart: // start time of a clip within vc (new field)
  vcEnd: 
}
```

Word times need to be recalculated:
- [x] When a paper-cut is added to the programmeScript (the addition plus all paper-cuts later in the script; in the last case, by the duration of the added clip)
    - To get new paper-cut timings:
      - [x] Get the `vc.end` time of the paper-cut previous in the script. This becomes its `vc.start`. 
      - [x] Words' new start times = (paperEdit.word.start - paperEdit.start) + vc.Start
      - [x] Words' new end times = start time + duration of word.
    - To modify paper-cut times following:
      - [x] Add the duration of the new paper-cut to each of the words' start and end times.
    - Index values also should be updated?? (I'm not sure what these are used for tbh)
- [x] When the programme script order is changed (everything between the clips being re-ordered? If the clips don't change in length, the video before and after the reordered elements should be the same)
  - [ ] Slice items between the indexes of changed paper-cuts.
  - [x] Recalculate word timings, vc.start and vc.end, plus indexes.
- [x] When an item is deleted (all words subtract that clip's duration from the start-time)
    - [x] All words after that paper-cut index should subtract the duration of that paper-cut from their words' start and end times, as well as their vc.start and vc.end times.
