### ISSUE TITLE
Items don't update on state change (e.g. add, remove, edit) in items.

### ISSUE THREAD

**Issue by emettely** [bbc/digital-paper-edit-client#90]
**Describe the bug**
Items don't update once you remove or add them. You have to manually refresh, which is bothersome.

**To Reproduce**
1. Run DPE locally (Firebase)
2. Delete one of the items or Create
3. See that nothing happens

**Expected behavior**
Update view on state change

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jamesdools** [comment]
What do you mean
> Run DPE locally (Firebase)

those are two separate things?
